### PR TITLE
fixed #8

### LINKED ISSUE #8: Add cut feature
Currently, this extension allows `copy` and `paste` operations in its API. We can add a `cut` function as well, so that users will be able to cut and paste a graph component. Some cases to consider during this operation:

- If selected elements contain compound nodes, their descendants should also be included to cut operation.
- If there are some edges that connect elements to be cut to other elements, such edges should be removed.
- `beforeCut` and `afterCut` options should be added (see current options).
- This operation should be undoable. 
- Update README and demo file to show this new feature.

### PR DESCRIPTION
**Pull request by AsmaJodeiri**

### CODE REVIEW

**Comment by AsmaJodeiri** [comment]
#8

**Review by hasanbalci — CHANGES_REQUESTED** [review]
@AsmaJodeiri I realized that normally (in master branch) the copied node becomes unselected and pasted node becomes selected, but in this PR copied node stays as selected and pasted node doesn't become selected. Can we change this to the original behavior for both copy-paste and cut-paste operations?

In addition, can you please revert the formatting of the code to its previous state? In the last commit, it seems that all code is deleted and written again in cytoscape-clipboard.js file probably because of the format changes (e.g. indentation amounts seems increased and also see the return statement in line 61).

**Comment by hasanbalci** [comment]
@AsmaJodeiri The selection problem seems solved. I realized a few problems with undo-redo:
- When we select a node and cut it, edges connected to that node are also removed. When we undo the operation, the node is restored but edges removed aren't restored. For a correct undo operation, those edges should be restored as well. 
- Another issue with undo-redo is: For example, I cut a node and then pasted it. If I undo the paste operation, then I should be able to paste it again. Currently, it cannot be done.

If you have questions about how the undo-redo extension works, you can ask me.

**Comment by AsmaJodeiri** [comment]
@hasanbalci I have added a version of cut which the undo-redo parts are fixed based on what you said but I am not sure how should edges act when a node is cuted. can you run the code and tell me if this is right or how should the edges act after cut?

**Comment by hasanbalci** [comment]
@AsmaJodeiri The functionality seems ok now. Maybe you can do the following to fix the format of the files:
- Get the original files (README.md, cytoscape-clipboard.js and demo.html) from the unstable branch
- Just apply your changes to the required places of the files without applying any formatting by you or your IDE
- Copy the updated files into your own copy of the repository and commit.

Hopefully, we can see only the actual changes in this way while keeping the original format. Additionally, it seems there are console log statements remaining in cytoscape-clipboard.js file, please remove them as well.

**Pull request merged**
